# Generated by Django 4.1 on 2023-03-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wastewise', '0002_spot_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wastewise.spot'),
        ),
    ]
